# Generated by Django 4.2.4 on 2023-10-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("author", models.CharField(blank=True, max_length=50, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("num_review", models.IntegerField(blank=True, null=True)),
                ("price", models.IntegerField(blank=True, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("genre", models.TextField(blank=True, null=True)),
            ],
        ),
    ]