<<<<<<< HEAD
# Generated by Django 4.2.4 on 2023-10-28 07:14
=======
# Generated by Django 4.2.4 on 2023-10-27 09:20
>>>>>>> eab82ff (update for review)

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ("main", "0001_initial"),
>>>>>>> eab82ff (update for review)
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=50)),
                ('review', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('rating_new', models.FloatField()),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_title", models.CharField(max_length=50)),
                ("review", models.TextField()),
                ("date_added", models.DateField(auto_now_add=True)),
                ("rating_new", models.FloatField()),
                (
                    "books",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.books"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
>>>>>>> eab82ff (update for review)
            ],
        ),
    ]
